In [3]:
import numpy as np

# Set random seed for consistency
np.random.seed(0)

# Number of training examples
m = 100  

# Generate feature values
x1 = np.random.uniform(0, 50, m)  # First feature
x2 = np.random.uniform(0, 50, m)  # Second feature

# Create feature matrix X (including bias term)
X_train = np.c_[np.ones(m), x1, x2]  # Shape: (m, 3)
print("First 5 rows of X_train (Feature Matrix):")
print(X_train[:5])

# True theta values for generating y
true_theta = np.array([4, 3, 5])  # Bias = 4, x1 coefficient = 3, x2 coefficient = 5

# Generate target values with noise
noise = np.random.normal(0, 5, m)  # Gaussian noise
y_train = X_train @ true_theta + noise  # Shape: (m,)
y_train = y_train.reshape(-1, 1)  # Reshape y_train into column vector
print("\nFirst 5 values of y_train (Target Values):")
print(y_train[:5])

# Compute gradient function for linear regression (MSE)
def compute_gradient(X, y, theta):
    m = len(y)
    h = X @ theta  # Linear prediction (no sigmoid)
    gradient = (1 / m) * (X.T @ (h - y))  # Gradient of MSE
    return gradient

# Compute Hessian function for linear regression (MSE)
def compute_hessian(X):
    m = X.shape[0]
    Hessian = (1 / m) * (X.T @ X)  # Hessian is constant for linear regression
    return Hessian

# Set number of iterations for Newton's Method
iterations = 10

# Initialize theta with zeros
theta_test = np.zeros((X_train.shape[1], 1))  # Shape (3, 1)
print("\nInitial theta_test (zeros):")
print(theta_test)

# Perform Newton's Method
for i in range(iterations):
    print(f"\n--- Iteration {i + 1} ---")
    
    # Compute predictions
    h = X_train @ theta_test
    print(f"Predictions (h):\n{h[:5]}")  # Print first 5 predictions

    # Compute the gradient
    gradient = compute_gradient(X_train, y_train, theta_test)
    print(f"Gradient:\n{gradient}")

    # Compute the Hessian matrix (constant for linear regression)
    Hessian = compute_hessian(X_train)
    print(f"Hessian Matrix:\n{Hessian}")
    
    # Optional regularization to avoid singularity (uncomment if needed)
    # lambda_reg = 0.01
    # Hessian += lambda_reg * np.eye(X_train.shape[1])

    # Compute the inverse of the Hessian
    H_inv = np.linalg.inv(Hessian)
    print(f"Inverse of Hessian (H_inv):\n{H_inv}")

    # Update theta using Newton's Method
    theta_test = theta_test - H_inv @ gradient
    print(f"Updated theta_test:\n{theta_test}")

# Final theta after all iterations
print("\nFinal theta after 10 iterations:")
print(theta_test)

# Compare with true theta
print("\nTrue theta:")
print(true_theta.reshape(-1, 1))

First 5 rows of X_train (Feature Matrix):
[[ 1.         27.4406752  33.89082684]
 [ 1.         35.75946832 13.50039866]
 [ 1.         30.1381688  36.75970111]
 [ 1.         27.24415915 48.10942726]
 [ 1.         21.18273997 12.43765718]]

First 5 values of y_train (Target Values):
[[261.4093394 ]
 [173.38074071]
 [272.47566868]
 [324.09051351]
 [127.24634353]]

Initial theta_test (zeros):
[[0.]
 [0.]
 [0.]]

--- Iteration 1 ---
Predictions (h):
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Gradient:
[[ -206.48850718]
 [-5427.66498552]
 [-6365.45835528]]
Hessian Matrix:
[[  1.          23.63969198  26.40408781]
 [ 23.63969198 766.62957534 611.00015967]
 [ 26.40408781 611.00015967 888.5955005 ]]
Inverse of Hessian (H_inv):
[[ 7.77489477e+00 -1.23054543e-01 -1.46413817e-01]
 [-1.23054543e-01  4.83356944e-03  3.32920049e-04]
 [-1.46413817e-01  3.32920049e-04  5.24705456e-03]]
Updated theta_test:
[[5.53652653]
 [2.94483545]
 [4.97411532]]

--- Iteration 2 ---
Predictions (h):
[[254.9216806 ]
 [177.9948161